[package]
name = "pipisenok-game"
version = "0.1.3"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = [ "wav" ] }
bevy_rapier2d = { version = "0.27.0", features = [ "simd-stable", "debug-render-2d" ] }
rand = "0.8.5"
log = "0.4.22"